# Generated by Django 5.0.6 on 2024-08-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nro_serie', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[('cable', 'Cable'), ('netbook', 'Netbook'), ('net', 'Net'), ('otros', 'Otros'), ('monitor', 'Monitor')], max_length=10)),
                ('estado', models.CharField(choices=[('reparacion', 'Reparacion'), ('disponible', 'Disponible'), ('prestado', 'Prestado')], max_length=10)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
