# Generated by Django 5.0.7 on 2024-08-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipamiento', '0002_alter_equipo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='categoria',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='lab',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
