# Generated by Django 5.0.7 on 2024-08-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipamiento', '0004_remove_equipo_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='laboratorio/'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='marca',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
